### PR TITLE
feat: Cookbook Onboard integration

### PR DESCRIPTION
**Pull request by AE-0h**
## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Walrus resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Walrus, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Walrus-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image

### CODE REVIEW

**Comment by mlegner** [comment]
Thanks a lot for the addition, @AE-0h. Unfortunately, this doesn't seem to play nicely with some mdBook keyboard shortcuts, in particular the [search](https://rust-lang.github.io/mdBook/guide/reading.html?highlight=search#search): When I type an `s` in the Cookbook integration, it still triggers the mdBook search, which captures my cursor. Any idea how to fix this?

**Comment by AE-0h** [comment]
> Thanks a lot for the addition, @AE-0h. Unfortunately, this doesn't seem to play nicely with some mdBook keyboard shortcuts, in particular the [search](https://rust-lang.github.io/mdBook/guide/reading.html?highlight=search#search): When I type an `s` in the Cookbook integration, it still triggers the mdBook search, which captures my cursor. Any idea how to fix this?
> 
> Here is a preview of the built site: https://mystenlabs.github.io/walrus-docs/pr-preview/pr-185/

Looking into it now, thanks for the catch!

**Comment by mlegner** [comment]
@AE-0h Did you find out anything regarding this issue?

**Comment by AE-0h** [comment]
> @AE-0h Did you find out anything regarding this issue? I've removed the integration for now and created a follow-up issue to re-add it: #187

yes it seems to be an issue with a hot key assignment for the s key in your docs sight.  Currently working on a patch on our repo to override the hot key assignment when our modal is open.

**Comment by mlegner** [comment]
> Currently working on a patch on our repo to override the hot key assignment when our modal is open.

Really nice, looking forward to the PR. 😀

**Pull request merged**
